FROM php:fpm-alpine

#* default workdir.
WORKDIR /var/www/html

#* Run the composer installation. 
#* if needed update plugin / vendor used
RUN php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');" && \
php composer-setup.php --install-dir=/usr/bin --filename=composer && \
php -r "unlink('composer-setup.php');"

#* copy all of the file in folder to working directory, in this case /var/www/html
COPY . .

RUN composer update